// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateHabit(arg1) {
  return window['go']['main']['App']['CreateHabit'](arg1);
}

export function DeleteHabit(arg1, arg2) {
  return window['go']['main']['App']['DeleteHabit'](arg1, arg2);
}

export function GetHabits(arg1) {
  return window['go']['main']['App']['GetHabits'](arg1);
}

export function GetTracks(arg1, arg2) {
  return window['go']['main']['App']['GetTracks'](arg1, arg2);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function ToggleTrack(arg1) {
  return window['go']['main']['App']['ToggleTrack'](arg1);
}
